version: '2'
services:
  proxy:
    build: ./proxy-container
    links: 
      - redis 
    ports:
      - 50103:3002
  hw3: 
    build: ./devops-hw3
    links: 
      - redis
    ports:
      - 50102:3000
  redis:
    image: redis
    ports: 
      - 32800:6379
volumes:
  logvolume01: {}
